### PR TITLE
Fix imported disk image indexing when disks are created in different data stores

### PR DESCRIPTION
**Pull request by nickewing**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Currently when creating a disk on one data store and then importing a disk on a different data store, the disk indexing is off causing the `qm set "$vm_id" "-scsi${disk_index}" "$disk_id"` command to fail.  This is because the non-imported disks are counted regardless of which data store they are on, but `qm importdisk` indexes disk images on a per data store basis.

For example given two disks, a non-imported disk1 on store1 and an imported disk2 on store2, the current code will import disk2 to store2 and expect the disk to be named `vm-${vm_id}-disk-1` but `qm importdisk` will have actually imported it as `vm-${vm_id}-disk-0` and the next common `qm set` will crash the terraform run.

This PR fixes this issue by counting each non-imported disk per data store and uses that count to determine the imported disk's index.

Release note for [CHANGELOG](https://github.com/danitso/terraform-provider-proxmox/blob/master/CHANGELOG.md):

```release-note
resource/virtual_environment_vm: Fix imported disk image indexing when disks are created in different data stores
```

### CODE REVIEW

**Comment by danitso-dp** [comment]
@nickewing I'll get back to this PR in the coming week to fix the conflict caused by the latest merges. You're welcome to fix it as well :)

**Comment by luhahn** [comment]
@danitso-dp  Please wait with merging this commit. Since another branch of mine reworks the whole indexing stuff in order to support mutliple disks in clones.

**Comment by danitso-dp** [comment]
@nickewing can you confirm that this is no longer an issue for you when using the latest version?

**Comment by nickewing** [comment]
@danitso-dp Just tried it out and it looks to work fine. Thanks!

**Pull request closed without merging**
