### PR TITLE
Release/v0.4.2

### PR DESCRIPTION
**Pull request by danitso-dp**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/danitso/terraform-provider-proxmox/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:

* resource/virtual_environment_vm: Fix `disk.file_id` diff issue
* resource/virtual_environment_vm: Fix disk resizing issue

OTHER:

* provider/example: Remove support for Terraform v0.11 and older
* provider/makefile: Update to use plugin caching to support local builds
```

### CODE REVIEW

**Comment by danitso-dp** [comment]
@luhahn @mleone87 any chance you're up for testing this patch release? It should fix the issue with `disk.file_id`, which @mleone87 mentioned in #61

**Comment by danitso-dp** [comment]
I'm merging this now as it has been confirmed to work in multiple clusters with different owners.

**Comment by mleone87** [comment]
@danitso-dp I confirm that it works! How did you managed to fix that?

**Comment by danitso-dp** [comment]
@mleone87 a simple workaround was left out when redesigning the disk management code. The fix is to only overwrite the value in the state file, if we actually have a new value for it. Considering the `file_id` value isn't stored in Proxmox, we cannot retrieve the original value during state refresh hence we shouldn't try to overwrite it.

**Pull request merged**
